---
- name: quit eye
  command: bash -lc "bundle exec eye quit -s"
  args:
    chdir: "{{ app_path }}"
  become: no
  ignore_errors: True

- name: ensure eye loads the config
  command: bash -lc "bundle exec eye l {{ eye_config_path }}"
  args:
    chdir: "{{ app_path }}"
  become: no

- name: ensure eye restarts
  command: bash -lc "bundle exec eye start all"
  args:
    chdir: "{{ app_path }}"
  become: no

