---
- name: stop eye
  command: bash -lc "bundle exec eye stop all"
  args:
    chdir: "{{ app_path }}"
  sudo: no
  ignore_errors: True

- name: quit eye
  command: bash -lc "bundle exec eye quit"
  args:
    chdir: "{{ app_path }}"
  sudo: no

- name: ensure eye loads the config
  command: bash -lc "bundle exec eye l {{ eye_config_path }}"
  args:
    chdir: "{{ app_path }}"
  sudo: no

- name: ensure eye restarts
  command: bash -lc "bundle exec eye start all"
  args:
    chdir: "{{ app_path }}"
  sudo: no

